### ISSUE TITLE
Remove dotted border on button

### ISSUE THREAD

**Issue by dwayne** [dwayne/elm-random-quote-machine#1]
![dotted-border-on-button](https://user-images.githubusercontent.com/319231/60660383-a8886380-9e25-11e9-822b-45e407cb8f11.png)

You can do the following:

```css
.button::-moz-focus-inner {
  border: 0;
}
```
